[package]
name = "asana-reporter"
version = "0.1.0"
authors = ["Jeremy Miller <jgmiller88@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
reqwest = "0.9.18"
serde = "1.0.92"
